apiVersion: v1
kind: Namespace
metadata:
  name: k8s-pod-logger

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-pod-logger
  namespace: k8s-pod-logger

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-pod-logger
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-pod-logger-pod-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-pod-logger
subjects:
- kind: ServiceAccount
  name: k8s-pod-logger
  namespace: k8s-pod-logger

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pod-logger
  namespace: k8s-pod-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-pod-logger
  template:
    metadata:
      labels:
        app: k8s-pod-logger
    spec:
      serviceAccountName: k8s-pod-logger
      containers:
      - name: k8s-pod-logger
        image: aakindele/k8s-pod-logger
        args:
        - -f=hello-world
        resources:
          requests:
            cpu: 500m
            memory: 500M
